version: '3.8'
services:
  apicultor:
    container_name: apiCultor
    build: .
    environment:
      TZ: Europe/Madrid
    ports:
      - 3333:3333
    volumes:
      - ./csvTickets:/usr/src/csvTickets
    restart: unless-stopped
